import tequila from "../assets/Tequila.webp";
import cognac from "../assets/cognac.webp";
import vodka from "../assets/vodka.webp";
import rum from "../assets/rum.jpg";
import vemouth from "../assets/vermouth.jpg";
import liqueur from "../assets/liqueur.jpg";
import whiskey from "../assets/Whisky.webp";
import beer from "../assets/beer.webp";
import winee from "../assets/winee.jpg";
import ginn from "../assets/ginn.jpg";

const alcohols = [
  {
    id: 0,
    name: "whiskey",
    image: whiskey,
    link: "#",
    types: [
      {
        name: "scotch whisky",
      },
      {
        name: "irish whiskey",
      },
      {
        name: "bourbon whiskey",
      },
    ],
    product: [
      {
        id: 0,
        name: "johnnie walker",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 1,
        name: "chivas regal",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 2,
        name: "jack daniels",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 3,
        name: "jameson",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 4,
        name: "jim beam",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 5,
        name: "bushmills",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 6,
        name: "Glenmorangie",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 7,
        name: "glenfiddich",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 8,
        name: "lagavulin",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 9,
        name: "balvenie",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
    ],
  },

  {
    id: 1,
    name: "gin",
    image: ginn,
    link: "#",
    types: [
      {
        name: "scotch whisky",
      },
      {
        name: "irish whiskey",
      },
      {
        name: "bourbon whiskey",
      },
    ],
    product: [
      {
        id: 0,
        name: "johnnie walker",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 1,
        name: "chivas regal",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 2,
        name: "jack daniels",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 3,
        name: "jameson",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 4,
        name: "jim beam",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 5,
        name: "bushmills",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 6,
        name: "Glenmorangie",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 7,
        name: "glenfiddich",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 8,
        name: "lagavulin",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 9,
        name: "balvenie",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
    ],
  },
  {
    id: 2,
    name: "cognac",
    image: cognac,
    link: "#",
    types: [
      {
        name: "armagnac",
      },
      {
        name: "brandy",
      },
      {
        name: "extra old",
      },
      {
        name: "luxory",
      },
    ],
    product: [
      {
        id: 0,
        name: "johnnie walker",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 1,
        name: "chivas regal",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 2,
        name: "jack daniels",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 3,
        name: "jameson",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 4,
        name: "jim beam",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 5,
        name: "bushmills",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 6,
        name: "Glenmorangie",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 7,
        name: "glenfiddich",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 8,
        name: "lagavulin",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 9,
        name: "balvenie",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
    ],
  },
  {
    id: 3,
    name: "rum",
    image: rum,
    link: "#",
    types: [
      {
        name: "white rum",
      },
      {
        name: "black rum",
      },
      {
        name: "dark rum",
      },
    ],
    product: [
      {
        id: 0,
        name: "johnnie walker",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 1,
        name: "chivas regal",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 2,
        name: "jack daniels",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 3,
        name: "jameson",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 4,
        name: "jim beam",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 5,
        name: "bushmills",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 6,
        name: "Glenmorangie",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 7,
        name: "glenfiddich",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 8,
        name: "lagavulin",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 9,
        name: "balvenie",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
    ],
  },
  {
    id: 4,
    name: "beer",
    image: beer,
    link: "#",
    types: [
      {
        name: "scotch whisky",
      },
      {
        name: "irish whiskey",
      },
      {
        name: "bourbon whiskey",
      },
    ],
    product: [
      {
        id: 0,
        name: "johnnie walker",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 1,
        name: "chivas regal",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 2,
        name: "jack daniels",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 3,
        name: "jameson",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 4,
        name: "jim beam",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 5,
        name: "bushmills",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 6,
        name: "Glenmorangie",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 7,
        name: "glenfiddich",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 8,
        name: "lagavulin",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 9,
        name: "balvenie",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
    ],
  },
  {
    id: 5,
    name: "vodka",
    image: vodka,
    link: "#",
    types: [
      {
        name: "scotch whisky",
      },
      {
        name: "irish whiskey",
      },
      {
        name: "bourbon whiskey",
      },
    ],
    product: [
      {
        id: 0,
        name: "johnnie walker",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 1,
        name: "chivas regal",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 2,
        name: "jack daniels",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 3,
        name: "jameson",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 4,
        name: "jim beam",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 5,
        name: "bushmills",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 6,
        name: "Glenmorangie",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 7,
        name: "glenfiddich",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 8,
        name: "lagavulin",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 9,
        name: "balvenie",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
    ],
  },
  {
    id: 6,
    name: "tequila",
    image: tequila,
    link: "#",
    types: [
      {
        name: "scotch whisky",
      },
      {
        name: "irish whiskey",
      },
      {
        name: "bourbon whiskey",
      },
    ],
    product: [
      {
        id: 0,
        name: "johnnie walker",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 1,
        name: "chivas regal",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 2,
        name: "jack daniels",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 3,
        name: "jameson",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 4,
        name: "jim beam",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 5,
        name: "bushmills",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 6,
        name: "Glenmorangie",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 7,
        name: "glenfiddich",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 8,
        name: "lagavulin",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 9,
        name: "balvenie",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
    ],
  },
  {
    id: 7,
    name: "liqueur",
    image: liqueur,
    link: "#",
    types: [
      {
        name: "scotch whisky",
      },
      {
        name: "irish whiskey",
      },
      {
        name: "bourbon whiskey",
      },
    ],
    product: [
      {
        id: 0,
        name: "johnnie walker",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 1,
        name: "chivas regal",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 2,
        name: "jack daniels",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 3,
        name: "jameson",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 4,
        name: "jim beam",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 5,
        name: "bushmills",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 6,
        name: "Glenmorangie",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 7,
        name: "glenfiddich",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 8,
        name: "lagavulin",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 9,
        name: "balvenie",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
    ],
  },
  {
    id: 8,
    name: "wine",
    image: winee,
    link: "#",
    types: [
      {
        name: "scotch whisky",
      },
      {
        name: "irish whiskey",
      },
      {
        name: "bourbon whiskey",
      },
    ],
    product: [
      {
        id: 0,
        name: "johnnie walker",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 1,
        name: "chivas regal",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 2,
        name: "jack daniels",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 3,
        name: "jameson",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 4,
        name: "jim beam",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 5,
        name: "bushmills",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 6,
        name: "Glenmorangie",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 7,
        name: "glenfiddich",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 8,
        name: "lagavulin",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 9,
        name: "balvenie",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
    ],
  },
  {
    id: 9,
    name: "vermouth",
    image: vemouth,
    link: "#",
    types: [
      {
        name: "scotch whisky",
      },
      {
        name: "irish whiskey",
      },
      {
        name: "bourbon whiskey",
      },
    ],
    product: [
      {
        id: 0,
        name: "johnnie walker",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 1,
        name: "chivas regal",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 2,
        name: "jack daniels",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 3,
        name: "jameson",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 4,
        name: "jim beam",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 5,
        name: "bushmills",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 6,
        name: "Glenmorangie",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 7,
        name: "glenfiddich",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 8,
        name: "lagavulin",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
      {
        id: 9,
        name: "balvenie",
        link: "#",
        image: "",
        price: 100,
        category: "",
      },
    ],
  },
];

export default alcohols;
